# version: '3.4'
services:

  # user: Administrator/Password1
  # https://pf.webinar.local:9999
  pfwebinarlocal:
    image: webinar/pf:latest
    container_name: pfwebinarlocal
    hostname: pf.webinar.local
    restart: on-failure
    networks:
      - webinar
    ports:
      - "9031:9031"
      - "9999:9999"
    environment:
      - "PF_RUN_PF_CONSOLE_TITLE=Webinar"
      - "PF_RUN_PF_ADMIN_BASEURL=https://${PF_ADMIN_NODE}"
    volumes:
      - ./products/pingfederate/pingfederate.lic:/opt/pingfederate/server/default/conf/pingfederate.lic
      - pf-out:/opt/pingfederate

  # https://openam.webinar.local:8449/openam/XUI/#login/
  # amAdmin, Password1
  openamwebinarlocal:
    image: webinar/openam:latest
    container_name: openamwebinarlocal
    hostname: openam.webinar.local
    restart: on-failure
    networks:
      - webinar
    ports:
      - "8449:8449"
    volumes:
      - ./dev/tlskey.p12:/usr/local/tomcat/ssl/tlskey.p12
      - am1-out:/forgerock
      - am2-out:/root/.openamcfg
      - am3-out:/usr/local/tomcat/webapps
    environment:
      - "SSL_PWD=${SSL_PWD}"
      - "SSL_PORT=8449"
      - "HOSTNAME=${HOSTNAME_AM}"

  # cn=administrator/ password
  # https://pd.webinar.local:9443/console
  pdwebinarlocal:
    image: webinar/pd:latest
    container_name: pdwebinarlocal
    hostname: pd.webinar.local
    restart: on-failure
    networks:
      - webinar
    ports:
      - "9443:9443"
      - "389:389"
      - "636:636"
    volumes:
      - ./products/pingdirectory/pingdirectory.lic:/opt/pingdirectory/licence.lic
      - pd-out:/opt/pingdirectory

  # https://playground.webinar.local:8448/OAuthPlayground
  oauthplayground:
    image: webinar/oauth-playground:latest
    container_name: playgroundwebinarlocal
    hostname: playground.webinar.local
    restart: on-failure
    networks:
      - webinar
    ports:
      - "8448:8448"
    environment:
      - "SSL_PWD=${SSL_PWD}"
      - "SSL_PORT=8448"
      - "HOSTNAME=${HOSTNAME_PLAYGROUND}"
    volumes:
      - ./dev/tlskey.p12:/usr/local/tomcat/ssl/tlskey.p12
      - opg-out:/usr/local/tomcat/webapps

networks:
  webinar:
    driver: bridge

volumes:
  pf-out:
    driver: local
    driver_opts:
      type: none
      device: /opt/mine/_project/forgerock-products/docker-out/pf
      o: bind
  pd-out:
    driver: local
    driver_opts:
      type: none
      device: /opt/mine/_project/forgerock-products/docker-out/pd
      o: bind
  opg-out:
    driver: local
    driver_opts:
      type: none
      device: /opt/mine/_project/forgerock-products/docker-out/opg
      o: bind
  am1-out:
    driver: local
    driver_opts:
      type: none
      device: /opt/mine/_project/forgerock-products/docker-out/am1
      o: bind
  am2-out:
    driver: local
    driver_opts:
      type: none
      device: /opt/mine/_project/forgerock-products/docker-out/am2
      o: bind
  am3-out:
    driver: local
    driver_opts:
      type: none
      device: /opt/mine/_project/forgerock-products/docker-out/am3
      o: bind